import type { Metadata } from "next";
import { headers } from "next/headers";
import { connection } from "next/server";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/shared/ui/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "FinControl", template: "%s · FinControl" },
  description: "Controle financeiro pessoal seguro e objetivo.",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // A nonce-based CSP requires request-time rendering so Next.js can attach the
  // nonce generated by proxy.ts to every framework and application script.
  await connection();
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange nonce={nonce}>
          {children}
          <Toaster richColors position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
